name: Hae ja julkaise ruokalistat

on:
  schedule:
    - cron: '55 3 * * 1-5'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Hae koodi
        uses: actions/checkout@v4

      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Asenna kirjastot
        run: pip install requests beautifulsoup4

      - name: Aja skripti ja luo HTML
        run: python scraper.py

      - name: Lataa tuotos Pagesiin
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Julkaise sivu
        uses: actions/deploy-pages@v4

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
