name: Hae ja julkaise ruokalistat

on:
  schedule:
    - cron: '55 3 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write  # Tämä on tärkeä muutos!
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hae koodi
        uses: actions/checkout@v4

      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Asenna kirjastot
        run: pip install requests beautifulsoup4

      - name: Aja skripti ja luo HTML
        run: python scraper.py

      - name: Lataa tuotos Pagesiin
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Julkaise sivu
        uses: actions/deploy-pages@v4

    # Tämä askel tekee tyhjän commitin, jos koodiin ei ole tullut muutoksia vähään aikaan
    #  - name: Keepalive Workflow
    #    uses: gautamkrishnar/keepalive-workflow@v1
